language: php

php:
  - 5.3
  - 5.4
  - 5.5

env:
  - SYMFONY_VERSION=2.3.*
  - SYMFONY_VERSION=2.4.*
  - SYMFONY_VERSION=dev-master

before_script:
  - composer require symfony/symfony:${SYMFONY_VERSION} --prefer-source
  - composer install --dev --prefer-source
  - sudo pip install -r docs/requirements.txt

script: phpunit && cd docs && sphinx-build -W -b html -d _build/doctrees . _build/html

notifications:
    webhooks: http://sonata-project.org/bundles/ecommerce/master/travis
